# -*- coding: utf-8 -*-
"""MoodHarmonics.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14nVX_Zj1PxWfEVNqDVtWG1DutUBPVcDq
"""

!pip install librosa tensorflow numpy transformers soundfile tqdm

import tensorflow as tf
import numpy as np
import librosa, os
from tqdm import tqdm
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from tensorflow.keras.utils import to_categorical
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout
from tensorflow.keras.optimizers import Adam
from google.colab import drive
drive.mount('/content/drive')

# Load YAMNet from TensorFlow Hub
import tensorflow_hub as hub
yamnet_model = hub.load('https://tfhub.dev/google/yamnet/1')

SAMPLE_RATE = 16000  # Required by YAMNet
GENRES = ['blues', 'classical', 'country', 'disco', 'hiphop',
          'jazz', 'metal', 'pop', 'reggae', 'rock']

def extract_yamnet_features(file_path):
    try:
        waveform, sr = librosa.load(file_path, sr=SAMPLE_RATE, mono=True)
        scores, embeddings, spectrogram = yamnet_model(tf.convert_to_tensor(waveform))
        return np.mean(embeddings.numpy(), axis=0)
    except Exception as e:
        print(f"Error processing {file_path}: {e}")
        return None

import os
import numpy as np
from sklearn.preprocessing import LabelEncoder
from tensorflow.keras.utils import to_categorical
from tqdm import tqdm


DATASET_PATH = "/content/drive/MyDrive/ISBInternshipAIML/Data/genres_original"
features, labels = [], []

for genre in GENRES:
    genre_path = os.path.join(DATASET_PATH, genre)
    print(f"Processing {genre}...")

    file_list = os.listdir(genre_path)
    for file in tqdm(file_list):
        if file.endswith((".wav", ".au")):
            fpath = os.path.join(genre_path, file)

            try:
                feat = extract_yamnet_features(fpath)

                if feat is not None:
                    features.append(feat)
                    labels.append(genre)

            except Exception as e:
                print(f"\nError processing {fpath}: {e}. Skipping file.")

print("\nFeature extraction complete.")

# Convert lists to NumPy arrays
X = np.array(features)

# Encode labels
le = LabelEncoder()
y = to_categorical(le.fit_transform(labels))

print(f"Processed {len(X)} files successfully.")

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.25, random_state=42, stratify=y)

model = Sequential([
    Dense(512, activation='relu', input_shape=(1024,)),
    Dropout(0.3),
    Dense(256, activation='relu'),
    Dropout(0.3),
    Dense(len(GENRES), activation='softmax')
])

model.compile(optimizer=Adam(learning_rate=0.001),
              loss='categorical_crossentropy',
              metrics=['accuracy'])

history = model.fit(
    X_train, y_train,
    validation_data=(X_test, y_test),
    epochs=20,
    batch_size=32,
    verbose=1
)
model.save("yamnet_gtzan_final.h5")

import matplotlib.pyplot as plt

test_loss, test_acc = model.evaluate(X_test, y_test)
print(f"Test Accuracy: {test_acc:.2%}")

plt.plot(history.history['accuracy'], label='Train')
plt.plot(history.history['val_accuracy'], label='Validation')
plt.title("Accuracy over Epochs")
plt.legend()
plt.show()

!pip install transformers accelerate torch soundfile

from transformers import AutoProcessor, MusicgenForConditionalGeneration
import torch
import soundfile as sf

processor = AutoProcessor.from_pretrained("facebook/musicgen-small")
musicgen = MusicgenForConditionalGeneration.from_pretrained("facebook/musicgen-small")

prompt = ""
inputs = processor(text=prompt, padding=True, return_tensors="pt")

audio_values = musicgen.generate(**inputs, max_new_tokens=30*50)
sf.write("generated_music.wav", audio_values[0, 0].numpy(), 32000)
print("Music generated and saved as generated_music.wav")

!pip install transformers torch accelerate

from transformers import GPT2Tokenizer, GPT2LMHeadModel

tokenizer = GPT2Tokenizer.from_pretrained("gpt2")
model = GPT2LMHeadModel.from_pretrained("gpt2")

def generate_lyrics(prompt, max_length=200):
    inputs = tokenizer.encode(prompt, return_tensors='pt')
    outputs = model.generate(
        inputs,
        max_length=max_length,
        temperature=0.8,
        top_p=0.9,
        do_sample=True,
        repetition_penalty=1.2
    )
    lyrics = tokenizer.decode(outputs[0], skip_special_tokens=True)
    return lyrics

prompt = "A bhangra beat with marriage song"

lyrics = generate_lyrics(f"Lyrics for {prompt}:")
print("Lyrics:\n", lyrics)

music_prompt = f"Instrumental background for: {prompt}"
inputs = processor(text=music_prompt, return_tensors="pt")
audio_values = musicgen.generate(**inputs, max_new_tokens=30 * 51)
sf.write("jazz_song.wav", audio_values[0, 0].numpy(), 32000)

print("Generated 30s music and lyrics for:", prompt)

